version: "3.5"
services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <REPLACE WITH YOUR MYSQL ROOT PASSWORD>
      MYSQL_USER: <REPLACE WITH YOUR MYSQL USER>
      MYSQL_PASSWORD: <REPLACE WITH YOUR MYSQL PASSWORD>
      MYSQL_DATABASE: <REPLACE WITH YOUR MYSQL DATABASE NAME>
    ports:
      - "3306:3306"
    volumes:
      - "./init_db.sql:/docker-entrypoint-initdb.d/1.sql"
